server:
  port: 8081

ribbon:
  eureka:
    enabled: false

zuul:
  host:
    connect-timeout-millis: 100
    socket-timeout-millis: 4000
  routes:
    sample:
      url: http://localhost:8080